### PR TITLE
German language added + language selector styling

### PR DESCRIPTION
**Pull request by mayuri2307**

### CODE REVIEW

**Comment by mayuri2307** [comment]
@mathkruger please review. Thanks!

**Comment by mayuri2307** [comment]
> Hey @mayuri2307, can you have a look on that comment I made? Just fix that and we're good to merge! Thanks for your contribution!

Hey @mathkruger sure, but unable to see the comment. Could you publish it again? Thank you!!

**Comment by mayuri2307** [comment]
@mathkruger Sorry couldn't see the comments 😅

**Comment by mathkruger** [comment]
@mayuri2307 it's a review comment on the [language-switcher.component.css](https://github.com/mathkruger/litefy/pull/62/files/ee27c3919e8cc4fd68c98ef456da668119c06476#diff-ff6396ac068cbab74c54809a989f61d99ecfa4794fb8501fd3652c756166516e) file.

**Comment by mayuri2307** [comment]
> @mayuri2307 it's a review comment on the [language-switcher.component.css](https://github.com/mathkruger/litefy/pull/62/files/ee27c3919e8cc4fd68c98ef456da668119c06476#diff-ff6396ac068cbab74c54809a989f61d99ecfa4794fb8501fd3652c756166516e) file.

I am still not able to see. Apologies!

**Pull request merged**
