### PR TITLE
UI/UX Improvement(Login Page)

### PR DESCRIPTION
**Pull request by ABSanthosh**
Made the Login page better and consistent/responsive.

### CODE REVIEW

**Comment by ABSanthosh** [comment]
Desktop
|Old|New  |
|--|--|
|  | enter image description here |

Mobile

|Old| New |
|--|--|
| </img>| </img> |

**Review by mathkruger — APPROVED** [review]
Thank you very much, it looks great!

**Comment by ABSanthosh** [comment]
@mathkruger Glad you liked it. I'll redo other pages as well but It'll take some time as I have my exams coming up.

I have some questions about the project.
In the chrome debug page, I saw a couple of .scss styles being applied like _reboot.scss and such. Is there any particular reason that you are using that? It uses a lot of "!important" and Its generally not a good practice to use "important" everywhere.

Also, I've added some text in en.json that might need translations.

**Comment by mathkruger** [comment]
This project is using bootstrap so maybe that's where these files are from.

**Comment by ABSanthosh** [comment]
Alright! I'll check it out.

**Pull request merged**
